export const STEP_DEFINITIONS = [
  {
    key: "CADASTRO",
    title: "Cadastro da Aula",
    description: "Cadastrar a arquitetura pedagógica da aula",
    order: 0,
    isManual: true,
    isAiEnabled: false,
    estimatedHours: 2,
    icon: "📋",
  },
  {
    key: "PRODUCAO_TEORIA",
    title: "Produção da Teoria",
    description: "Produzir material teórico no padrão TI TOTAL",
    order: 1,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 10,
    icon: "📖",
  },
  {
    key: "PADRONIZACAO_EDITORIAL",
    title: "Padronização Editorial",
    description: "Aplicar padrão editorial TI TOTAL na teoria",
    order: 2,
    isManual: false,
    isAiEnabled: false,
    estimatedHours: 2,
    icon: "🎨",
  },
  {
    key: "SELECAO_QUESTOES",
    title: "Seleção de Questões",
    description: "IA seleciona e classifica questões representativas",
    order: 3,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 1,
    icon: "🔍",
  },
  {
    key: "CADERNOS_QUESTOES",
    title: "Cadernos de Questões",
    description: "Criar cadernos organizados por tópico e banca",
    order: 4,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 1,
    icon: "📚",
  },
  {
    key: "PREPARACAO_EDITORIAL",
    title: "Preparação Editorial",
    description: "Limpar e padronizar as questões",
    order: 5,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 1,
    icon: "✏️",
  },
  {
    key: "COMENTARIOS_QUESTOES",
    title: "Comentários das Questões",
    description: "Comentar questões usando a teoria produzida",
    order: 6,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 6,
    icon: "💬",
  },
  {
    key: "MONTAGEM_PDFS",
    title: "Montagem dos PDFs",
    description: "Montar arquivos finais textuais da aula",
    order: 7,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 3,
    icon: "📄",
  },
  {
    key: "SLIDES",
    title: "Slides da Aula",
    description: "Criar apresentação de slides para gravação",
    order: 8,
    isManual: false,
    isAiEnabled: true,
    estimatedHours: 2,
    icon: "🖥️",
  },
  {
    key: "REVISAO_HUMANA",
    title: "Revisão Humana",
    description: "Revisão final dos materiais pela equipe",
    order: 9,
    isManual: true,
    isAiEnabled: false,
    estimatedHours: 2,
    icon: "👁️",
  },
  {
    key: "GRAVACAO",
    title: "Gravação da Aula",
    description: "Gravação em vídeo pelo professor",
    order: 10,
    isManual: true,
    isAiEnabled: false,
    estimatedHours: 4,
    icon: "🎥",
  },
  {
    key: "PUBLICACAO",
    title: "Publicação",
    description: "Publicar aula completa na plataforma",
    order: 11,
    isManual: false,
    isAiEnabled: false,
    estimatedHours: 1,
    icon: "🚀",
  },
] as const;

export const ROLE_LABELS: Record<string, string> = {
  ADMIN: "Administrador",
  COORDENADORA: "Coordenadora",
  ASSISTENTE_EDITORIAL: "Assistente Editorial",
  REVISOR: "Revisor",
  VISUALIZADOR: "Visualizador",
};

export const STATUS_LABELS: Record<string, string> = {
  NAO_INICIADA: "Não Iniciada",
  EM_ANDAMENTO: "Em Andamento",
  AGUARDANDO_APROVACAO: "Aguardando Aprovação",
  REPROVADA: "Reprovada",
  EM_CORRECAO: "Em Correção",
  APROVADA: "Aprovada",
  BLOQUEADA: "Bloqueada",
};

export const STATUS_COLORS: Record<string, string> = {
  NAO_INICIADA: "bg-gray-100 text-gray-600",
  EM_ANDAMENTO: "bg-blue-100 text-blue-700",
  AGUARDANDO_APROVACAO: "bg-yellow-100 text-yellow-700",
  REPROVADA: "bg-red-100 text-red-700",
  EM_CORRECAO: "bg-orange-100 text-orange-700",
  APROVADA: "bg-green-100 text-green-700",
  BLOQUEADA: "bg-gray-200 text-gray-500",
};

export const LESSON_STATUS_LABELS: Record<string, string> = {
  RASCUNHO: "Rascunho",
  EM_PRODUCAO: "Em Produção",
  AGUARDANDO_REVISAO: "Aguardando Revisão",
  REVISANDO: "Revisando",
  CONCLUIDA: "Concluída",
  PUBLICADA: "Publicada",
};

export const BOARD_LABELS: Record<string, string> = {
  CEBRASPE: "CEBRASPE",
  FGV: "FGV",
  FCC: "FCC",
  VUNESP: "VUNESP",
  CESPE: "CESPE",
  OUTROS: "Outros",
};
